### ISSUE TITLE
when can it support 6.0.0 

### ISSUE THREAD

**Issue by chenchuangc** [jolicode/emoji-search#20]
i am sorry for ask this question but my elasticsearch is 6.0.0

**Comment by damienalexandre** [comment]
Hi there,
I didn't got the time to test the plugin with 6.0 yet, and can't say when it's going to happen.

Thanks for opening the issue as this is definitely on my to-do list :+1:

**Comment by damienalexandre** [comment]
HEY!
I just managed to get a build working for 6.1.2 :muscle: 
https://github.com/jolicode/emoji-search/releases/tag/6.1.2

Enjoy :wink:

**Comment by chenchuangc** [comment]
thank you very much i am really so happy that you have paid attention on my question, thank you
