### ISSUE TITLE
An Emoji capable tokenizer

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/emoji-search#3]
We need a specific tokenizer to handle emoji properly in Elasticsearch, here is the specification.
# Emoji Tokenizer

Should be based on the [standard tokenizer](https://lucene.apache.org/core/5_0_0/analyzers-common/org/apache/lucene/analysis/standard/StandardTokenizer.html) to keep the grammar logic and  [Unicode Text Segmentation](http://unicode.org/reports/tr29/) implementation.

But add support for symbols / emoji as specified in [tr51](http://www.unicode.org/reports/tr51/).
# Test cases

| Input | Tokens |
| --- | --- |
| Get some donut's. | `Get` `some` `donut's` |
| Get some 🍩's. | `Get` `some` `🍩's` |
| "🍩" | `🍩` |

**Comment by damienalexandre** [comment]
Currently working on a ICU 58 based tokenizer with additional custom rules to consider emoji & their combinaisons as word/token. 
Elasticsearch's ICU plugin is out of date (ICU 54), Lucene ICU too (ICU 56), so I will have to ship my own ICU with the plugin, my only concern is about compatibility...

:yum:

**Comment by gibrown** [comment]
@damienalexandre did you manage to build an ICU tokenizer that supports emoji tokenization by any chance?

**Comment by damienalexandre** [comment]
Yes! The plugin documentation is here: https://github.com/jolicode/emoji-search/tree/master/esplugin

**Comment by gibrown** [comment]
Looks really cool! Thanks! Adding to our project list to try it out.
